# Modern Probability

## Some important collections of sets 

Throughout, $\Omega\ne \phi$ is any set, and $\mathcal{A}\subseteq 2^\Omega$ is
used to denote a collection of subsets of $\Omega$.

<!--defining sigma algebras--> 

::: {.definition #sigma-algebra name="Sigma algebras"}

A collection $\mathcal{A}\subseteq 2^\Omega$ is said to be a *$\sigma$-algebra* if it satisfies the following
conditions:

1. $\Omega\in\mathcal{A}$.
2. $\mathcal{A}$ is closed under complements.
3. $\mathcal{A}$ is closed under countable unions.

Intuitively, $\sigma$-algebras are used to define the collection
of events of a random experiment which might be of interest to us.

:::

<!--generated sigma algebras-->

::: {.theorem #generated-sigma-algebra name="Generated Sigma Algebras"}

Let $\mathcal{E}\subset 2^\Omega$ be any collection of sets. Then there exists a
smallest $\sigma$-algebra $\sigma(\mathcal{E})$ with 
$\mathcal{E}\subset\sigma(\mathcal{E})$, particularly:

\begin{equation}
\begin{split}
    \sigma(\mathcal{E}) := \bigcap_{\mathcal{A}\subset 2^\Omega\text{ is a $\sigma$-algebra}\\ \quad\quad\mathcal{A}\supset \mathcal{E}}\mathcal{A}
\end{split}
(\#eq:label)
\end{equation}

$\sigma(\mathcal{E})$ is called the $\sigma$-algebra **generated** by $\mathcal{E}$.

:::

<!--lim sup and inf-->

::: {.definition #liminf name="liminf and limsup"}

Let $(A_n)_{n\in\mathbb{N}}$ be a sequence of subsets
of $\Omega$. Then

\begin{equation}
\begin{split}
    A_* := \liminf_{n\to\infty}A_n &:= \bigcup_{n = 1}^{\infty} \bigcap_{m = n}^{\infty} A_m\\
    A^* := \limsup_{n\to\infty}A_n &:= \bigcap_{n = 1}^{\infty} \bigcup_{m = n}^{\infty} A_m
\end{split}
(\#eq:liminf)
\end{equation}

Equivalently,

\begin{equation}
\begin{split}
    A_* := \liminf_{n\to\infty}A_n &= \left\{\omega\in\Omega: \#\left\{n\in\mathbb{N}: \omega\notin A_n\right\} < \infty\right\}\\
    A^* := \limsup_{n\to\infty}A_n &= \left\{\omega\in\Omega: \#\left\{n\in\mathbb{N}: \omega\notin A_n\right\} = \infty\right\}
\end{split}
(\#eq:liminf-equiv)
\end{equation}

Or, in simple words, the *limes inferior* is the event where *eventually all of the
$A_n$ occur*, and the *limes superior* is the event when *infinitely many of the $A_n$
occur*.

:::

::: {.lemma}
Let $\mathcal{A}$ be a $\sigma$-algebra, and let $(A_n)_{n\in\mathbb{N}}$ be a
sequence of sets such that $A_n\in \mathcal{A}$. Then, $A_*\in\mathcal{A}$ and 
$A^*\in\mathcal{A}$.

:::

<!--generated by topologies in metric spaces-->

::: {.definition #borel-sigma-algebra name="Borel Sigma Algebra"}

Let $d$ be a metric on $\Omega$, and let $B_r(x)$ denote an open ball in $\Omega$
of radius $r$ centered at $x$. The usual class of open sets is a topology:

\begin{equation}
\begin{split}
\tau &= \left\{\bigcup_{(x, r)\in F} B_r(x): F\subset \Omega\times (0, \infty)\right\} 
\end{split}
(\#eq:label)
\end{equation}

making $(\Omega, \tau)$ a topological spaec. The $\sigma$-algebra

\begin{equation}
\begin{split}
\mathcal{B}(\Omega) := \mathcal{B}(\omega, \tau) := \sigma(\tau) 
\end{split}
(\#eq:label)
\end{equation}

generated by open sets is called the ***Borel $\sigma$-algebra*** on $\Omega$. Sets
$A\in\mathcal{B}(\Omega, \tau)$ are called ***Borel sets*** or ***Borel measurable 
sets***.

:::

<!--trace/restriction of class of sets-->

::: {.definition #trace name="Trace of a class of sets"}

Let $\mathcal{A}\subset 2^\Omega$ be an arbitrary class of subsets of $\Omega$ and
let $A\in 2^\Omega\setminus \{\phi\}$. The class

\begin{equation}
\begin{split}
\mathcal{A}|_{A} := \left\{A\cap B: B\in\mathcal{A}\right\}\subset 2^A
\end{split}
(\#eq:label)
\end{equation}

is called the ***trace*** or ***restriction*** of $\mathcal{A}$ onto $A$.

:::

::: {.theorem}

Let $A\subset \Omega$ be a non-empty set and let $\mathcal{A}$ be a $\sigma$-algebra.
Then the trace $\mathcal{A}|_{A}$ is a $\sigma$-algebra on $A$.

:::

## Set Functions

The goal of *set functions* is to assign weights to each *event* of a $\sigma$-algebra.
This development eventually leads to what we call *probability spaces*.

::: {.definition #set-functions-defn}

Let $\mathcal{A}\subset 2^\Omega$ be a class of sets and let 
$\mu:\mathcal{A}\to[0, \infty]$ be a set function. Then, $\mu$ is

1. ***monotone*** if $\mu(A)\le \mu(B)$ for any two sets $A, B\in\mathcal{A}$ with 
    $A\subset B$.

2. ***additive*** if $\mu\left(\biguplus_{i = 1}^n A_i\right) = \sum_{i = 1}^n \mu(A_i)$ 
    for any choice of finitely many mutually disjoint sets $(A_i)_{i = 1}^n\in\mathcal{A}$
    with $\bigcup_{i = 1}^n A_i\in \mathcal{A}$.

3. ***$\sigma$-additive*** if 
    $\mu\left(\biguplus_{i = 1}^\infty A_i\right) = \sum_{i = 1}^\infty \mu(A_i)$
    for any choice of countably many mutually disjoint sets 
    $(A_i)_{i = 1}^\infty\in\mathcal{A}$ with $\bigcup_{i = 1}^\infty A_i\in \mathcal{A}$.

4. ***subadditive*** if for any choice of finitely many sets $A\in\mathcal{A}$,
    $(A_i)_{i = 1}^n\in\mathcal{A}$ with $A\subseteq \bigcup_{i = 1}^n A_i$
    we have $\mu(A)\le \sum_{i = 1}^n \mu(A_i)$.

5. ***$\sigma$-subadditive*** if for any choice of countably many sets $A\in\mathcal{A}$,
    $(A_i)_{i = 1}^\infty\in\mathcal{A}$ with $A\subseteq \bigcup_{i = 1}^\infty A_i$
    we have $\mu(A)\le \sum_{i = 1}^\infty \mu(A_i)$.

:::

::: {.remark}

The notion of *countably many objects* becomes important when we move from
discrete spaces to uncoutable spaces (like $\mathbb{R}^n$). It's *impossible*
to assign probability weights to *all* subsets of an uncountable space, and still
have a working theory of probability. For this reason, we must choose a much smaller
(countable) collection of events which are interesting to work with.

:::

::: {.definition #measure name="Measures"}

Let $\mathcal{A}$ be a $\sigma$-algebra. A set function $\mu:\mathcal{A}\to[0, \infty]$
is called a ***measure*** on $\mathcal{A}$ if it satisfies the following conditions:

1. $\mu(\phi) = 0$.
2. $\mu$ is $\sigma$-additive. 

Furthermore, $\mu$ is called a ***probability measure*** if $\mu(\Omega) = 1$. $\mu$
is said to be ***finite*** if $\mu(A) < \infty$ for every $A\in\mathcal{A}$, and $\mu$
is said to be $\sigma$-finite if there exists a sequence of sets 
$(\Omega_n)_{n = 1}^\infty\in\mathcal{A}$ such that 
$\Omega = \bigcup_{n = 1}^\infty\Omega_n$ and $\mu(\Omega_n) < \infty$ for all 
$n\in\mathbb{N}$.

:::
